// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Program = 2,
  Opcode = 3,
  A = 4,
  ImmediateByte = 5,
  ImmediateWord = 6,
  Byte = 7,
  Word = 8,
  Long = 9,
  X = 10,
  Y = 11,
  S = 12
