// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Instruction = 2,
  A = 3,
  ImmediateByte = 4,
  ImmediateWord = 5,
  Byte = 6,
  Word = 7,
  Long = 8,
  X = 9,
  S = 10,
  Y = 11,
  Comment = 17
